format_code_in_doc_comments = true
format_strings = true
control_brace_style = "ClosingNextLine"
single_line_if_else_max_width = 60
struct_lit_width = 32
use_field_init_shorthand = true
wrap_comments = true
